Repository benavlabs/crudadmin, pull requests merged in 2025-06, with the labels that each got.

#6 remove installing from docs
  docs/installing.md
  mkdocs.yml
Labels: documentation

#7 api overview page
  docs/api/overview.md
Labels: documentation

#8 change from personal to benavlabs
  CONTRIBUTING.md
  README.md
  docs/api/overview.md
  docs/index.md
  mkdocs.yml
  pyproject.toml
Labels: documentation

#10 add instructions for installing dependencies using UV
  CONTRIBUTING.md
Labels: documentation

#15 Docs fix
  README.md
  crudadmin/admin_interface/crud_admin.py
  docs/index.md
  docs/quick-start.md
  docs/usage/admin-users.md
  docs/usage/configuration.md
Labels: documentation

#20 add video to docas
  docs/index.md
Labels: documentation

#23 Warning gitignore
  .gitignore
  README.md
  docs/quick-start.md
  docs/usage/configuration.md
Labels: documentation

#24 fix Python 3.9 and 3.10 compatibility issues
  crudadmin/admin_interface/admin_site.py
  crudadmin/admin_interface/crud_admin.py
  crudadmin/admin_user/models.py
  crudadmin/core/schemas/timestamp.py
  crudadmin/event/decorators.py
  crudadmin/event/models.py
  crudadmin/event/service.py
  crudadmin/session/backends/database.py
  crudadmin/session/backends/memory.py
  crudadmin/session/manager.py
  crudadmin/session/models.py
  crudadmin/session/schemas.py
  tests/auth/test_endpoints.py
  tests/conftest.py
  tests/event/test_service.py
  tests/session/test_integration.py
  tests/session/test_manager.py
Labels: enhancement

#28 track `.python-version` in Git and clarify Python version requirements in docs
  .gitignore
  .python-version
  CONTRIBUTING.md
Labels: enhancement

#32 select_schema functional
  crudadmin/admin_interface/crud_admin.py
  crudadmin/admin_interface/model_view.py
  docs/usage/adding-models.md
  pyproject.toml
  tests/crud/test_select_schema.py
Labels: enhancement

#34 add support for root mount
  crudadmin/admin_interface/admin_site.py
  crudadmin/admin_interface/crud_admin.py
  crudadmin/admin_interface/middleware/auth.py
  crudadmin/admin_interface/model_view.py
  tests/crud/test_admin.py
  tests/crud/test_root_mount_path.py
Labels: bug

#35 fix location of icon
  crudadmin/templates/auth/login.html
  crudadmin/templates/base/base.html
  pyproject.toml
Labels: bug

#38 fix uuid, add test
  crudadmin/admin_interface/model_view.py
  tests/conftest.py
  tests/crud/test_uuid_support.py
Labels: bug

#41 add session backends to mkdocs.yml
  mkdocs.yml
Labels: documentation

#43 Add configs to init
  README.md
  crudadmin/__init__.py
  docs/index.md
  docs/usage/common-patterns.md
  docs/usage/session-backends.md
  pyproject.toml
Labels: enhancement

#44 Fix(UI): correct dashboard URLs when mounted at root
  crudadmin/admin_interface/admin_site.py
  crudadmin/admin_interface/crud_admin.py
  crudadmin/admin_interface/model_view.py
  crudadmin/templates/admin/dashboard/dashboard.html
  crudadmin/templates/admin/dashboard/dashboard_content.html
  crudadmin/templates/admin/management/events.html
  crudadmin/templates/admin/management/events_content.html
  crudadmin/templates/admin/management/health.html
  crudadmin/templates/admin/model/components/list_content.html
  crudadmin/templates/admin/model/components/pagination.html
  crudadmin/templates/admin/model/create.html
  crudadmin/templates/admin/model/list.html
  crudadmin/templates/admin/model/update.html
  crudadmin/templates/auth/login.html
  crudadmin/templates/base/base.html
Labels: bug

#46 add tests for the event system integration
  tests/event/test_integration.py
Labels: enhancement
